{% set name = "servicestack" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c1fb072efa64643dba3dec234b57d17bc7b39d6ed85866b1ed613c5c1d36b7b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - dataclasses >=0.6
    - dataclasses-json >=0.5.4
    - marshmallow >=3.12.2
    - python >=3.9
    - requests >=2.25.1

test:
  imports:
    - servicestack
  commands:
    - python -m unittest tests.test_serialization.TestSerialization

about:
  home: https://github.com/ServiceStack/servicestack-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ServiceStack Python Service Clients
  doc_url: https://github.com/ServiceStack/servicestack-python
  dev_url: https://github.com/ServiceStack/servicestack-python

extra:
  recipe-maintainers:
    - mythz
    - Layoric
